### ISSUE TITLE
Consumer un-deploy

### ISSUE THREAD

**Issue by zdavep** [dcshock/forklift#15]
When a consumer is un-deployed from forklift, the connection to the MQ server remains open.  Need a cleanup call when the consumer's message loop terminates.

**Comment by dcshock** [comment]
Shouldn't the broker connection remain open in this case? That way any other consumers that are deployed already have a connection available?

**Comment by zdavep** [comment]
Sure, a connection pool would work, but currently they aren't getting re-used.  Every un-deploy/re-deploy creates a new connection to the broker.

**Comment by zdavep** [comment]
Basically, all that's necessary is a finally block in the message loop that calls close() on the message consumer parameter.

**Comment by zdavep** [comment]
Fixed in commit 05645f86862b8d93315c4770e377378a328036b1
